### ISSUE TITLE
Segfault on exit

### ISSUE THREAD

**Issue by KyleFromKitware** [Kitware/seal-tk#17]
When closing the main window, a segfault occurs. It has been traced back to #4.

Cc: @mwoehlke-kitware

**Comment by mwoehlke-kitware** [comment]
#4 is most likely a red herring... if it's the issue I think it is (for which I have a fix, somewhere), it's actually #3 at fault. The reason it isn't seen before #4 is because the `Window` never gets deleted.

**Comment by KyleFromKitware** [comment]
#3 was merged after #4. The segfault happened once #4 was merged, before #3 was merged.

**Comment by mwoehlke-kitware** [comment]
If this is the crash we're talking about:

```
Invalid read of size 8
   at 0x4876AD9: sealtk::gui::PlayerPrivate::destroyResources() (Player.cpp:397)
   by 0x5D2C1C2: call (qobjectdefs_impl.h:376)
   by 0x5D2C1C2: QMetaObject::activate(QObject*, int, int, void**) (qobject.cpp:3754)
   by 0x570C1EB: QOpenGLContext::destroy() (qopenglcontext.cpp:647)
   by 0x570C5AA: QOpenGLContext::~QOpenGLContext() (qopenglcontext.cpp:691)
   by 0x570C5CC: QOpenGLContext::~QOpenGLContext() (qopenglcontext.cpp:696)
   by 0x51132CF: QOpenGLWidgetPrivate::reset() (qopenglwidget.cpp:719)
   by 0x5113358: QOpenGLWidget::~QOpenGLWidget() (qopenglwidget.cpp:1006)
   by 0x4853288: sealtk::noaa::gui::Player::~Player() (Player.cpp:92)
 Address 0x2b56e780 is 0 bytes inside a block of size 312 free'd
   at 0x4839EFC: operator delete(void*) (vg_replace_malloc.c:586)
   by 0x4877FE7: cleanup (qscopedpointer.h:60)
   by 0x4877FE7: ~QScopedPointer (qscopedpointer.h:107)
   by 0x4877FE7: sealtk::gui::Player::~Player() (Player.cpp:92)
   by 0x4853288: sealtk::noaa::gui::Player::~Player() (Player.cpp:92)
```

...I'm almost certain it isn't "caused" by #4. Maybe it's been latent since ever.

Basically, we have a slot to clean up GL stuff when the context goes away, which it does when our widget (`Player`) goes away, but because the context is destroyed by the base class, by that time our `PlayerPrivate` is already gone:

1. Start destroying `Player`
1. Members of `Player` (`d_ptr` → `PlayerPrivate`) destroyed
1. Start destroying `Player`'s "near" base (`QOpenGLWidget`)
1. Start destroying the associated context
1. `QOpenGLContext::aboutToBeDestroyed` fires
1. Start destroying `Player`'s "far" base (`QObject`)
1. Connections attached to `Player` disconnected

The problem is that (5) happens before (7), but after (2), at which point we're in a problematic state where the "real" receiver of the slot (`PlayerPrivate`) no longer exists. The fix is to make (7) happen earlier, either by doing it "manually" rather than waiting for (6) to do it, or possibly by making `PlayerPrivate` be itself a `QObject`.

**Comment by KyleFromKitware** [comment]
Yeah, I'm sure that it wasn't caused by #4. It was just exposed by it.
